on:
  push:
    branches:
      - "development"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install angular CLI
        run: npm i -g @angular/cli

      - name: Build
        run: ng build --configuration staging

      - name: Lint
        run: ng lint

      - name: Test
        run: ng test -- --browsers=ChromeHeadless --watch=false --code-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Git
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ github.actor }}

      - name: Tag build
        run: |
          git tag -a build-${{ github.run_number }} -m "Tag for github build-${{ github.run_number }}"
          git push origin build-${{ github.run_number }}

      - name: Deploy to staging
        run: aws s3 cp dist/delay-frontend s3://delaygram-staging/ --recursive; aws cloudfront create-invalidation --distribution-id E2VCGQ0ORDECMP --paths \"/*\"'

      - name: Tag release
        run: |
          git tag -a release-${{ github.run_number }} -m "Tag for github release-${{ github.run_number }}"
          git push origin release-${{ github.run_number }}

      - name: Publish test results
        run: |
          aws s3 cp coverage/delay-frontend s3://delaygram-testresults/frontend/build-${{ github.run_number }} --recursive
